/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_RG_windowNU (void);
GtkWidget* create_SR_windowListeElectorale (void);
GtkWidget* create_SR_windowAL (void);
GtkWidget* create_RG_Ajout_Observateur (void);
GtkWidget* create_RG_EA1 (void);
GtkWidget* create_RG_windowCSU (void);
GtkWidget* create_OZ_windowER (void);
GtkWidget* create_OZ_windowER1 (void);
GtkWidget* create_OZ_windowAR (void);
GtkWidget* create_OZ_windowMR (void);
GtkWidget* create_OZ_windowCSR (void);
GtkWidget* create_FS_windowBVacc (void);
GtkWidget* create_FS_windowBVaj (void);
GtkWidget* create_FS_windowBVmod (void);
GtkWidget* create_FS_windowBVsupp (void);
GtkWidget* create_RG_GestionUser (void);
GtkWidget* create_RG_windowPrincipale (void);
GtkWidget* create_RG_windowEspaceAdmin (void);
GtkWidget* create_RG_windowGestionO (void);
GtkWidget* create_Stat__stiques (void);
GtkWidget* create_RG_windowModifUser (void);
GtkWidget* create_RG_windowEspaceBV (void);
GtkWidget* create_RG_windowDemade_modif (void);
GtkWidget* create_SR_windowAI (void);
GtkWidget* create_SR_windowSupprimer (void);
GtkWidget* create_SR_windowCSU (void);
GtkWidget* create_SR_windowModifier (void);
GtkWidget* create_SR_windowAFFICHER (void);
GtkWidget* create_SR_WINDOWchercher (void);
GtkWidget* create_HB_windowGE (void);
GtkWidget* create_HB_windowAE (void);
GtkWidget* create_HB_windowME (void);
GtkWidget* create_HB_windowSE (void);
